# Generated by Django 6.1 on 2026-08-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'gasto')], max_length=10)),
                ('categoria', models.CharField(choices=[('salario', 'Salario'), ('bonos', 'bonos'), ('inversiones', 'Inversiones'), ('comida', 'Comida'), ('transporte', 'Transporte'), ('alquiler', 'Alquiler'), ('otros', 'Otros')], max_length=20)),
                ('fecha', models.DateField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
